// ================================================================================
//  Tag
//
//  Tables:
//      Tag - Entity
// ================================================================================

Table "Tag" {
    "Id" integer [primary key, not null]
    "Caption" text [not null]
    "PlaceholderMarker" text [null]
    "CreatedOn" text [not null, default: "STRFTIME('%F %T+00:00', 'now')"]
    "UpdatedOn" text [not null, default: "STRFTIME('%F %T+00:00', 'now')"]

    //  Constraints {
    //      "PK_Tag" [primary key constraint]
    //      "AK_Tag_Caption" [alternate key constraint]
    //      "CK_Tag_Caption_NotEmpty" [check constraint, sql: "LENGTH(TRIM(\"Caption\")) > 0"]
    //      "CK_Tag_Caption_MaxLength" [check constraint, sql: "LENGTH(TRIM(\"Caption\")) <= 256"]
    //      "CK_Tag_PlaceholderMarker_NullOrNotEmpty" [check constraint, sql: "\"PlaceholderMarker\" IS NULL OR LENGTH(TRIM(\"PlaceholderMarker\")) > 0"]
    //      "CK_Tag_PlaceholderMarker_NullOrMaxLength" [check constraint, sql: "\"PlaceholderMarker\" IS NULL OR LENGTH(TRIM(\"PlaceholderMarker\")) <= 2048"]
    //  }
}


// ================================================================================
//  Character
//
//  Tables:
//      Character - Entity
//      CharacterTag - Relationship
//      CharacterGroup - Entity
//
//  References:
//      FK_Character_CharacterGroup_CharacterGroupId
//      FK_CharacterTag_Character_CharacterId
//      FK_CharacterTag_Tag_TagId
// ================================================================================

Table "Character" {
    "Id" integer [primary key, not null]
    "CharacterGroupId" integer [null]
    "Symbol" text [not null]
    "Type" integer [not null]
    "Pronunciation" text [null]
    "Syllable" text [null]
    "Onyomi" text [null]
    "Kunyomi" text [null]
    "Meaning" text [null]
    "CreatedOn" text [not null, default: "STRFTIME('%F %T+00:00', 'now')"]
    "UpdatedOn" text [not null, default: "STRFTIME('%F %T+00:00', 'now')"]

    //  Constraints {
    //      "PK_Character" [primary key constraint]
    //      "FK_Character_CharacterGroup_CharacterGroupId" [foreign key constraint]
    //      "CK_Character_Symbol_NotEmpty" [check constraint, sql: "LENGTH(TRIM(\"Symbol\")) > 0"]
    //      "CK_Character_Symbol_MaxLength" [check constraint, sql: "LENGTH(TRIM(\"Symbol\")) <= 16"]
    //      "CK_Character_Pronunciation_NullOrNotEmpty" [check constraint, sql: "\"Pronunciation\" IS NULL OR LENGTH(TRIM(\"Pronunciation\")) > 0"]
    //      "CK_Character_Pronunciation_NullOrMaxLength" [check constraint, sql: "\"Pronunciation\" IS NULL OR LENGTH(TRIM(\"Pronunciation\")) <= 32"]
    //      "CK_Character_Syllable_NullOrNotEmpty" [check constraint, sql: "\"Syllable\" IS NULL OR LENGTH(TRIM(\"Syllable\")) > 0"]
    //      "CK_Character_Syllable_NullOrMaxLength" [check constraint, sql: "\"Syllable\" IS NULL OR LENGTH(TRIM(\"Syllable\")) <= 32"]
    //      "CK_Character_Onyomi_NullOrNotEmpty" [check constraint, sql: "\"Onyomi\" IS NULL OR LENGTH(TRIM(\"Onyomi\")) > 0"]
    //      "CK_Character_Onyomi_NullOrMaxLength" [check constraint, sql: "\"Onyomi\" IS NULL OR LENGTH(TRIM(\"Onyomi\")) <= 256"]
    //      "CK_Character_Kunyomi_NullOrNotEmpty" [check constraint, sql: "\"Kunyomi\" IS NULL OR LENGTH(TRIM(\"Kunyomi\")) > 0"]
    //      "CK_Character_Kunyomi_NullOrMaxLength" [check constraint, sql: "\"Kunyomi\" IS NULL OR LENGTH(TRIM(\"Kunyomi\")) <= 256"]
    //      "CK_Character_Meaning_NullOrNotEmpty" [check constraint, sql: "\"Meaning\" IS NULL OR LENGTH(TRIM(\"Meaning\")) > 0"]
    //      "CK_Character_Meaning_NullOrMaxLength" [check constraint, sql: "\"Meaning\" IS NULL OR LENGTH(TRIM(\"Meaning\")) <= 512"]
    //  }

    Indexes {
        "CharacterGroupId" [name: "IX_Character_CharacterGroupId"]
    }
}

Ref "FK_Character_CharacterGroup_CharacterGroupId" {
    "Character"."CharacterGroupId" > "CharacterGroup"."Id"
}

Table "CharacterTag" {
    "CharacterId" integer [primary key, not null]
    "TagId" integer [primary key, not null]

    //  Constraints {
    //      "PK_CharacterTag" [primary key constraint]
    //      "FK_CharacterTag_Character_CharacterId" [foreign key constraint]
    //      "FK_CharacterTag_Tag_TagId" [foreign key constraint]
    //  }

    Indexes {
        "CharacterId" [name: "IX_CharacterTag_CharacterId"]
        "TagId" [name: "IX_CharacterTag_TagId"]
    }
}

Ref "FK_CharacterTag_Character_CharacterId" {
    "CharacterTag"."CharacterId" > "Character"."Id"
}

Ref "FK_CharacterTag_Tag_TagId" {
    "CharacterTag"."TagId" > "Tag"."Id"
}

Table "CharacterGroup" {
    "Id" integer [primary key, not null]
    "Caption" text [not null]
    "Comment" text [null]
    "Enabled" integer [not null]
    "CreatedOn" text [not null, default: "STRFTIME('%F %T+00:00', 'now')"]
    "UpdatedOn" text [not null, default: "STRFTIME('%F %T+00:00', 'now')"]

    //  Constraints {
    //      "PK_CharacterGroup" [primary key constraint]
    //      "AK_CharacterGroup_Caption" [alternate key constraint]
    //      "CK_CharacterGroup_Caption_NotEmpty" [check constraint, sql: "LENGTH(TRIM(\"Caption\")) > 0"]
    //      "CK_CharacterGroup_Caption_MaxLength" [check constraint, sql: "LENGTH(TRIM(\"Caption\")) <= 256"]
    //      "CK_CharacterGroup_Comment_NullOrNotEmpty" [check constraint, sql: "\"Comment\" IS NULL OR LENGTH(TRIM(\"Comment\")) > 0"]
    //      "CK_CharacterGroup_Comment_NullOrMaxLength" [check constraint, sql: "\"Comment\" IS NULL OR LENGTH(TRIM(\"Comment\")) <= 2048"]
    //  }
}


// ================================================================================
//  Word
//
//  Tables:
//      Word - Entity
//      WordTag - Relationship
//      WordGroup - Entity
//
//  References:
//      FK_Word_WordGroup_WordGroupId
//      FK_WordTag_Word_WordId
//      FK_WordTag_Tag_TagId
// ================================================================================

Table "Word" {
    "Id" integer [primary key, not null]
    "WordGroupId" integer [null]
    "Characters" text [not null]
    "CharacterTypes" integer [not null]
    "Pronunciation" text [null]
    "Meaning" text [null]
    "CreatedOn" text [not null, default: "STRFTIME('%F %T+00:00', 'now')"]
    "UpdatedOn" text [not null, default: "STRFTIME('%F %T+00:00', 'now')"]

    //  Constraints {
    //      "PK_Word" [primary key constraint]
    //      "FK_Word_WordGroup_WordGroupId" [foreign key constraint]
    //      "CK_Word_Characters_NotEmpty" [check constraint, sql: "LENGTH(TRIM(\"Characters\")) > 0"]
    //      "CK_Word_Characters_MaxLength" [check constraint, sql: "LENGTH(TRIM(\"Characters\")) <= 256"]
    //      "CK_Word_Pronunciation_NullOrNotEmpty" [check constraint, sql: "\"Pronunciation\" IS NULL OR LENGTH(TRIM(\"Pronunciation\")) > 0"]
    //      "CK_Word_Pronunciation_NullOrMaxLength" [check constraint, sql: "\"Pronunciation\" IS NULL OR LENGTH(TRIM(\"Pronunciation\")) <= 512"]
    //      "CK_Word_Meaning_NullOrNotEmpty" [check constraint, sql: "\"Meaning\" IS NULL OR LENGTH(TRIM(\"Meaning\")) > 0"]
    //      "CK_Word_Meaning_NullOrMaxLength" [check constraint, sql: "\"Meaning\" IS NULL OR LENGTH(TRIM(\"Meaning\")) <= 512"]
    //  }

    Indexes {
        "WordGroupId" [name: "IX_Word_WordGroupId"]
    }
}

Ref "FK_Word_WordGroup_WordGroupId" {
    "Word"."WordGroupId" > "WordGroup"."Id"
}

Table "WordTag" {
    "WordId" integer [primary key, not null]
    "TagId" integer [primary key, not null]

    //  Constraints {
    //      "PK_WordTag" [primary key constraint]
    //      "FK_WordTag_Word_WordId" [foreign key constraint]
    //      "FK_WordTag_Tag_TagId" [foreign key constraint]
    //  }

    Indexes {
        "WordId" [name: "IX_WordTag_WordId"]
        "TagId" [name: "IX_WordTag_TagId"]
    }
}

Ref "FK_WordTag_Word_WordId" {
    "WordTag"."WordId" > "Word"."Id"
}

Ref "FK_WordTag_Tag_TagId" {
    "WordTag"."TagId" > "Tag"."Id"
}

Table "WordGroup" {
    "Id" integer [primary key, not null]
    "Caption" text [not null]
    "Comment" text [null]
    "Enabled" integer [not null]
    "CreatedOn" text [not null, default: "STRFTIME('%F %T+00:00', 'now')"]
    "UpdatedOn" text [not null, default: "STRFTIME('%F %T+00:00', 'now')"]

    //  Constraints {
    //      "PK_WordGroup" [primary key constraint]
    //      "AK_WordGroup_Caption" [alternate key constraint]
    //      "CK_WordGroup_Caption_NotEmpty" [check constraint, sql: "LENGTH(TRIM(\"Caption\")) > 0"]
    //      "CK_WordGroup_Caption_MaxLength" [check constraint, sql: "LENGTH(TRIM(\"Caption\")) <= 256"]
    //      "CK_WordGroup_Comment_NullOrNotEmpty" [check constraint, sql: "\"Comment\" IS NULL OR LENGTH(TRIM(\"Comment\")) > 0"]
    //      "CK_WordGroup_Comment_NullOrMaxLength" [check constraint, sql: "\"Comment\" IS NULL OR LENGTH(TRIM(\"Comment\")) <= 2048"]
    //  }
}
